---
# gather facts about the current release
- name: get the releases custom values
  command: "helm get values {{ hr_name }} --output json {{ hr_global_flags | join(' ') }}"
  changed_when: false
  register: cmd_release_values

- name: set the release facts
  set_fact:
    found_release_facts:
      name: "{{ cmd_releases_infos.Name }}"
      chart:
        # this 2 may break :/ =>
        name: "{{ (cmd_releases_infos.Chart).rsplit('-', 1)[0]}}"
        version: "{{ (cmd_releases_infos.Chart).split('-')|last }}"
      namespace: "{{ cmd_releases_infos.Namespace }}"
      found_values: "{{cmd_release_values.stdout | from_json}}"
  vars:
    cmd_releases_infos: "{{(cmd_helm_releases.stdout | from_json)| json_query(json_query_request)| first}}"
    json_query_request: "Releases[?Name == '{{hr_name}}']"
